// <auto-generated />
namespace GarbagePickup.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateddatabasewithfalseaddressandusers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateddatabasewithfalseaddressandusers));
        
        string IMigrationMetadata.Id
        {
            get { return "201709141243429_updated database with false address and users"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
